DROP DATABASE IF EXISTS 03_library; 

CREATE DATABASE IF NOT EXISTS 03_library DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci; 

USE 03_library;

CREATE TABLE IF NOT EXISTS genre (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    type VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS book (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    isbn VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    genre_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE IF NOT EXISTS member (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    card_id INT UNSIGNED NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(100),
    email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS borrow (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    borrow_date DATE NOT NULL,
    period INT UNSIGNED NOT NULL,
    member_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE IF NOT EXISTS book_pile (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    book_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (book_id) REFERENCES book(id),
    borrow_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (borrow_id) REFERENCES borrow(id),
    amount VARCHAR(25) NOT NULL
);