DROP DATABASE IF EXISTS videoteka; 

CREATE DATABASE IF NOT EXISTS videoteka DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci; 

USE videoteka;

CREATE TABLE IF NOT EXISTS zanr (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    tip VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS film (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ime VARCHAR(50) NOT NULL,
    godina CHAR(5) NOT NULL,
    zanr_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (zanr_id) REFERENCES zanr(id)
);

CREATE TABLE IF NOT EXISTS medij (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    tip VARCHAR(25) NOT NULL,
    koeficijent FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS zaliha (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    film_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (film_id) REFERENCES film(id),
    medij_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (medij_id) REFERENCES medij(id),
    kolicina INT NOT NULL
);

CREATE TABLE IF NOT EXISTS clan (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    clanski_broj CHAR(15) NOT NULL UNIQUE,
    ime VARCHAR(50) NOT NULL,
    adresa VARCHAR(100),
    email VARCHAR(50) NOT NULL UNIQUE,
    telefon VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS cjenik (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    tip VARCHAR(25) NOT NULL,
    cijena DECIMAL(10, 2),
    zakasnina DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS posudba (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    datum_posudba DATE NOT NULL,
    datum_povrat DATE NOT NULL,
    clan_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (clan_id) REFERENCES clan(id),
    zaliha_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (zaliha_id) REFERENCES zaliha(id),
    cjenik_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (cjenik_id) REFERENCES cjenik(id)
);