DROP DATABASE IF EXISTS videoteka; 

CREATE DATABASE IF NOT EXISTS videoteka DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci; 

USE videoteka;

CREATE TABLE IF NOT EXISTS grad ( 
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    postanski_broj VARCHAR(10) NOT NULL,
    ime VARCHAR(25) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS clan ( 
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ime VARCHAR(30) NOT NULL,  
    prezime VARCHAR(50) NOT NULL,
    oib VARCHAR(15) NOT NULL,  
    broj_telefona VARCHAR(15),
    email VARCHAR(50),
    adresa VARCHAR(100) NOT NULL,
    grad_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (grad_id) REFERENCES grad(id)
) ENGINE=InnoDB; 

CREATE TABLE IF NOT EXISTS film ( 
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,  
    ime VARCHAR(50) NOT NULL,  
    zanr VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS medij ( 
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,  
    naziv VARCHAR(10) NOT NULL 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cjenik ( 
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,  
    usluga VARCHAR(50) NOT NULL,  
    medij_id INT UNSIGNED,
    FOREIGN KEY (medij_id) REFERENCES medij(id),
    cijena DECIMAL(10, 2) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS kolicina ( 
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,  
    film_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (film_id) REFERENCES film(id),
    medij_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (medij_id) REFERENCES medij(id),
    kolicina INT UNSIGNED
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS posudba ( 
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,  
    clan_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (clan_id) REFERENCES clan(id),
    film_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (film_id) REFERENCES film(id),
    cjenik_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (cjenik_id) REFERENCES cjenik(id),
    datum DATETIME
) ENGINE=InnoDB;